# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  # - name: Home Page
  #   url: /
  #   weight: 10
  - name: Instructor & Office Hours
    url: docs/instructor-info
    weight: 10
  - name: Syllabus
    url: static/uploads/IDS2935_syllabus.pdf
    identifier: syllabus
    weight: 20
  - name: Schedule & Readings
    url: docs/schedule
    weight: 30
  - name: Assignments
    url: docs/assignments
    weight: 40
  - name: Quest Info & SLOs
    url: docs/quest_slo_info
    weight: 50
  